### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by jixunmoe**
Commits:
* Added Chinese Translation
* ~~Force a locale by specifying a language id using `sdmc:/3ds/locale.bin`.~~

~~`locale.bin`: Value of ([CFG_Language](https://github.com/smealum/ctrulib/blob/master/libctru/include/3ds/services/cfgu.h#L20)) in ASCII hex (1 character long, 1 Byte) or the actual language id (1 Byte).~~

~~For example, to set the language to `CFG_LANGUAGE_TW`, you can open the file as notepad and type `B`, or fire a hex editor and fill in `0B`.~~

Know Issue:
* ~~Due to font missing some characters in EUR console (not sure about JPN or other regions), some of the characters will display as a question mark.~~

### CODE REVIEW

**Comment by fincs** [comment]
Thank you very much for your contribution. A couple of things though:

- ZH can only be set as language on CHN region 3DSes, likewise TW is for TWN region 3DSes.
- CHN system font and TWN system font are different from the JPN/USA/EUR system font and the KOR system font. It is normal that the characters used in CHN/TWN are not available.
- I'm a bit confused because of the translations not matching character by character (simpified/traditional); are these intended to be two separate languages (Mandarin/Cantonese)? For TWN, I'd suggest to go with whichever language Nintendo used in their official translation of 3DS system software.
- I would not like to have the locale.bin feature to keep it consistent with the rest of the system and also because of the system font problem.

**Comment by jixunmoe** [comment]
1. OK.
2. OK.
3. There are some phases that does not match exactly for use in TW and Mainland. E.g. port ([CN](https://zh.wikipedia.org/zh-cn/%E9%80%9A%E8%A8%8A%E5%9F%A0): 连接端口/接口/端口/协议端口; [TW](https://zh.wikipedia.org/zh-tw/%E9%80%9A%E8%A8%8A%E5%9F%A0): 連接埠/介面/埠/協定埠)
4. I can remove that part of code.

**Comment by fincs** [comment]
Ok, thank you again. I am merging this now.

**Comment by fincs** [comment]
A new string was added. Can you translate this to ZH/TW, please?

`Offline, waiting for network…`

**Pull request merged**
