### PR TITLE
Make README more beginner friendly

### PR DESCRIPTION
**Pull request by n0toose**
The Homebrew Launcher is most likely the most popular homebrew application for the Nintendo 3DS.

Many years ago, it was a great starting point for me before attempting to write my own "hello world" type of application, but I kept getting stuck. I now know how to contribute back, so this is my attempt at authoring the things I wish I would have read back then.

- Use GitHub-styled admonition boxes in the introduction and in the build instructions
- Include some resources explaining where the person wanting to build the launcher by themselves would have to go if they are just starting out. The Homebrew Launcher was a personal starting point back then, and I would presume that this would be the case for others too.
- Environment variables can be an issue if you are not using specific kinds of systems that seem to be supported by devkitPro.

In the case of `make` and environment variables, I explained some things that would seem pretty self-explanatory to most developers, but there are (and were) tinkerers that can be very young. In the cases of chose to explain the technical terms, some details and the theory behind them. It contains enough pointers for the reader to look up what they need for their own setup online.

### CODE REVIEW

**Comment by n0toose** [comment]
I would be happy to adjust or shorten the content if it is believed that they are verbose; I'll mention that the person I wrote this for a curious tinkerer that is young, or, in this age, an older person that just pulled their old console out of the drawer.

**Comment by WinterMute** [comment]
This isn't an appropriate place to be attempting to create tutorials for using devkitPro toolchains.

**Comment by n0toose** [comment]
I understand why some parts of my PR are out-of-scope, but wouldn't it be possible to bring this PR to an acceptable state if I refocused on things that previously existed in the README and removed background information like:
- the excerpt about `.3ds` files
- the excerpt about environment variables are?
- the excerpt about Makefiles

Other than that, I'd think that my work bases itself on top of other work that was already present in the README file (+ I tried to link to devkitPro resources to reduce the maintenance burden here) - do you think that I could do anything to salvage parts of my work and bring it to a state where it can be merged?

**Comment by WinterMute** [comment]
> I understand why some parts of my PR are out-of-scope, but wouldn't it be possible to bring this PR to an acceptable state if I refocused on things that previously existed in the README and removed background information like:

I don't really see how tbh. Like I said this readme isn't the place to be writing tutorials on how to use devkitPro toolchains and libraries. We should ideally have more documentation and tutorial material hosted on devkitpro.org but we lack resources and people with the necessary time, inclination, knowledge and skill. This is just one 3ds project of many & not something we'd recommend as a starting point - that's what the provided examples are for.

This is vastly out of scope for a PR on a project. This is part of what the [devkitPro forums](https://devkitpro.org/index.php) are for.

**Comment by n0toose** [comment]
I totally get why you'd see part of my changes amount to a tutorial / "designating this project as a starting point". I would say that my changes improved some preexisting instructions and that the well-intended "tutorial-ish" stuff seemingly "tainted" the core of what I was trying to get at, but I guess we'll have to agree to disagree here.

Disappointing news for me, but **AT** the end of the day, it's your call and it's not like I'm entitled to anything here. Thanks for the detailed response.

**Pull request closed without merging**
